theme: jekyll-theme-minimal
title: The Official Cat Duty Website
description: Bookmark this site or subscribe to my <a href="https://www.youtube.com/@Puddlecast">YouTube channel Puddlecast</a> to keep an eye on my project updates! <a href="https://www.catduty.com">catduty.com</a> was sadly already taken.
